package fi.lipp.blog.model.exceptions

class UserNotFoundException : BlogException("User not found", 404)
