package fi.lipp.blog.model.exceptions

class WrongUserException : BlogException("User not found", 404)
